/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deadly21;

import static deadly21.InterfazMenuDeadly21.lista;
import static deadly21.InterfazMenuDeadly21.mazo;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Agustín
 */
public class InterfazPartidaDeadly21 extends javax.swing.JFrame {
    

    /**
     * Creates new form InterfazPartidaDeadly21
     */
    public InterfazPartidaDeadly21() {
        initComponents();
        Oponente.setText(lista.parejaJugador().obtenerNombre());
        lb_Jugador.setText(lista.obtenerNombreParticipante(0));
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoColor = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Carta2 = new javax.swing.JLabel();
        Carta3 = new javax.swing.JLabel();
        Carta4 = new javax.swing.JLabel();
        Carta5 = new javax.swing.JLabel();
        Carta1 = new javax.swing.JLabel();
        Carta6 = new javax.swing.JLabel();
        Carta7 = new javax.swing.JLabel();
        Carta8 = new javax.swing.JLabel();
        Carta9 = new javax.swing.JLabel();
        Carta10 = new javax.swing.JLabel();
        Jugador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Oponente = new javax.swing.JLabel();
        lb_Jugador = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoColor.setBackground(new java.awt.Color(153, 153, 153));
        fondoColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Quedarse");
        fondoColor.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 258, 91));

        jButton2.setText("Pedir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        fondoColor.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 258, 91));

        Carta2.setBackground(new java.awt.Color(102, 0, 102));
        Carta2.setForeground(new java.awt.Color(153, 102, 255));
        Carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 100, 150));

        Carta3.setBackground(new java.awt.Color(102, 0, 102));
        Carta3.setForeground(new java.awt.Color(153, 102, 255));
        Carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 100, 150));

        Carta4.setBackground(new java.awt.Color(102, 0, 102));
        Carta4.setForeground(new java.awt.Color(153, 102, 255));
        Carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 100, 150));

        Carta5.setBackground(new java.awt.Color(102, 0, 102));
        Carta5.setForeground(new java.awt.Color(153, 102, 255));
        Carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 100, 150));

        Carta1.setBackground(new java.awt.Color(102, 0, 102));
        Carta1.setForeground(new java.awt.Color(153, 102, 255));
        Carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, 100, 150));

        Carta6.setBackground(new java.awt.Color(102, 0, 102));
        Carta6.setForeground(new java.awt.Color(153, 102, 255));
        Carta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 100, 150));

        Carta7.setBackground(new java.awt.Color(102, 0, 102));
        Carta7.setForeground(new java.awt.Color(153, 102, 255));
        Carta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 100, 150));

        Carta8.setBackground(new java.awt.Color(102, 0, 102));
        Carta8.setForeground(new java.awt.Color(153, 102, 255));
        Carta8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 100, 150));

        Carta9.setBackground(new java.awt.Color(102, 0, 102));
        Carta9.setForeground(new java.awt.Color(153, 102, 255));
        Carta9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 100, 150));

        Carta10.setBackground(new java.awt.Color(102, 0, 102));
        Carta10.setForeground(new java.awt.Color(153, 102, 255));
        Carta10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 100, 150));
        fondoColor.add(Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 190, 120));
        fondoColor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 190, 120));
        fondoColor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        Oponente.setText("Nombre");
        fondoColor.add(Oponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 90, -1));

        lb_Jugador.setText("Nombre");
        fondoColor.add(lb_Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 680, -1, -1));

        jButton3.setText("tablas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        fondoColor.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondoColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /*JDialog dialogo = new JDialog();
        JPanel panel = new JPanel();
        JLabel etiqueta = new JLabel("Error, debe ingresar su nombre y apellido");
        JLabel etiqueta1 = new JLabel("Error, debe una cedula valida");
        JButton boton = new JButton("Cerrar");
        boton.addActionListener((ActionEvent e) -> {
            dialogo.dispose();
        });
        panel.add(etiqueta);
        panel.add(boton);
        dialogo.add(panel, BorderLayout.CENTER);
        dialogo.setSize(300, 100);
        
           
            dialogo.setVisible(true);*/
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Duelos().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carta1;
    private javax.swing.JLabel Carta10;
    private javax.swing.JLabel Carta2;
    private javax.swing.JLabel Carta3;
    private javax.swing.JLabel Carta4;
    private javax.swing.JLabel Carta5;
    private javax.swing.JLabel Carta6;
    private javax.swing.JLabel Carta7;
    private javax.swing.JLabel Carta8;
    private javax.swing.JLabel Carta9;
    private javax.swing.JLabel Jugador;
    private javax.swing.JLabel Oponente;
    private javax.swing.JPanel fondoColor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb_Jugador;
    // End of variables declaration//GEN-END:variables
}
