/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deadly21;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Agustín
 */
public class InterfazMenuDeadly21 extends javax.swing.JFrame {

    /**
     * Creates new form interfazDeadly21
     */
    
    static File fichero = new File("archivos");
    static String barra = File.separator;
    static String ubicacion = System.getProperty("user.dir")+barra+"archivos"+barra;
    
    static MazoDeCartas mazo= new MazoDeCartas();
    static ListaParticipantes lista = new ListaParticipantes();
    static ListaParticipantes listaInicial = new ListaParticipantes();
    static ListaParticipantes listaSemis = new ListaParticipantes();
    static ListaParticipantes listaFinal = new ListaParticipantes();
    static Scanner scan = new Scanner(System.in);
    
    private static void cargarParticipantes(){
        int numParticipantes=0;
        
        try {
            BufferedReader lector = new BufferedReader(new FileReader(ubicacion + "jugadores.in.txt"));
            
            while (numParticipantes<7){
                lista.ingresarAlPrincipio(lector.readLine(),lector.readLine());
                System.out.println(lector.readLine());
                
                numParticipantes++;
            }            
            
            lector.close();
            
            System.out.println("Ingrese su nombre");
            lista.ingresarAlPrincipio(scan.nextLine(), null);
            
          
            
            
            
        } catch (IOException e) { 
           
        }
    }
    
    public static void igualar(int indice, ListaParticipantes lis){
        for(int i = 0; i<indice; i++){
            lis.ingresarAlFinal(lista.competidor(i+1).nombre, lista.competidor(i+1).actitud);
        }
    }
    
    public InterfazMenuDeadly21() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoColor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Iniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoColor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Deadly 21");

        Btn_Iniciar.setText("Empezar Partida");
        Btn_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoColorLayout = new javax.swing.GroupLayout(fondoColor);
        fondoColor.setLayout(fondoColorLayout);
        fondoColorLayout.setHorizontalGroup(
            fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoColorLayout.createSequentialGroup()
                .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoColorLayout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel1))
                    .addGroup(fondoColorLayout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(Btn_Iniciar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoColorLayout.setVerticalGroup(
            fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoColorLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addGap(184, 184, 184)
                .addComponent(Btn_Iniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IniciarActionPerformed
        // TODO add your handling code here:
        Btn_Iniciar.setVisible(false);
        new InterfazPartidaDeadly21().setVisible(true);
    }//GEN-LAST:event_Btn_IniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuDeadly21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuDeadly21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuDeadly21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuDeadly21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InterfazMenuDeadly21().setVisible(true);
        });
        
        
        
        cargarParticipantes();
        
        if(fichero.mkdir()){
            System.out.println("Se creo");
        }
        
        try {
            BufferedWriter escritor = new BufferedWriter(new FileWriter(ubicacion + "ganadores.out.txt"));
            escritor.write("jugador");
            escritor.close();
        } catch (IOException ex) {
            Logger.getLogger(InterfazMenuDeadly21.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

        
        igualar(8,listaInicial);
        lista.emparejar();
        lista.imprimirLista();
        lista.duelos();
        
        new Duelos().setVisible(true);
        
        /*
        Participante ko = lista.ko(0);
        listaEliminados.ingresarAlFinal(ko.nombre, ko.actitud);
        System.out.println(listaEliminados.competidor(0).nombre);
        
        ko = lista.ko(1);
        listaEliminados.ingresarAlFinal(ko.nombre, ko.actitud);
        System.out.println(listaEliminados.competidor(0).nombre);
        
        ko = lista.ko(2);
        listaEliminados.ingresarAlFinal(ko.nombre, ko.actitud);
        System.out.println(listaEliminados.competidor(0).nombre);
        
        ko = lista.ko(3);
        listaEliminados.ingresarAlFinal(ko.nombre, ko.actitud);
        System.out.println(listaEliminados.competidor(0).nombre);
        */
        lista.ko(0);
         lista.ko(1);
         lista.ko(2);
         lista.ko(3);
         igualar(4,listaSemis);
         lista.emparejar();
         lista.duelos();
         new Duelos().setVisible(true);
         /*
         ko = lista.ko(0);
         listaEliminados.ingresarAlFinal(ko.nombre, ko.actitud);
         
         ko = lista.ko(1);
         listaEliminados.ingresarAlFinal(ko.nombre, ko.actitud);
         */
         lista.ko(0);
         lista.ko(1);
         igualar(2,listaFinal);
         lista.emparejar();
         lista.duelos();
         new Duelos().setVisible(true);
         
         lista.ko(0);
         new Duelos().setVisible(true);
         
         
        
        for (int i=0; i<lista.largo;i++){
                System.out.println("\n " + "[" + i +"] " + lista.obtenerNombreParticipante(i) + " C, " + lista.obtenerParejaParticipante(i));
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Iniciar;
    private javax.swing.JPanel fondoColor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
