/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deadly21;

/**
 *
 * @author Agustín
 */
public class InterfazPartidaDeadly21 extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPartidaDeadly21
     */
    public InterfazPartidaDeadly21() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoColor = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Carta2 = new javax.swing.JLabel();
        Carta3 = new javax.swing.JLabel();
        Carta4 = new javax.swing.JLabel();
        Carta5 = new javax.swing.JLabel();
        Carta1 = new javax.swing.JLabel();
        Carta6 = new javax.swing.JLabel();
        Carta7 = new javax.swing.JLabel();
        Carta8 = new javax.swing.JLabel();
        Carta9 = new javax.swing.JLabel();
        Carta10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoColor.setBackground(new java.awt.Color(153, 153, 153));
        fondoColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        fondoColor.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 258, 91));

        jButton2.setText("  ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        fondoColor.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 258, 91));

        Carta2.setBackground(new java.awt.Color(102, 0, 102));
        Carta2.setForeground(new java.awt.Color(153, 102, 255));
        Carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 100, 150));

        Carta3.setBackground(new java.awt.Color(102, 0, 102));
        Carta3.setForeground(new java.awt.Color(153, 102, 255));
        Carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 100, 150));

        Carta4.setBackground(new java.awt.Color(102, 0, 102));
        Carta4.setForeground(new java.awt.Color(153, 102, 255));
        Carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 100, 150));

        Carta5.setBackground(new java.awt.Color(102, 0, 102));
        Carta5.setForeground(new java.awt.Color(153, 102, 255));
        Carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 100, 150));

        Carta1.setBackground(new java.awt.Color(102, 0, 102));
        Carta1.setForeground(new java.awt.Color(153, 102, 255));
        Carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, 100, 150));

        Carta6.setBackground(new java.awt.Color(102, 0, 102));
        Carta6.setForeground(new java.awt.Color(153, 102, 255));
        Carta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 100, 150));

        Carta7.setBackground(new java.awt.Color(102, 0, 102));
        Carta7.setForeground(new java.awt.Color(153, 102, 255));
        Carta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 100, 150));

        Carta8.setBackground(new java.awt.Color(102, 0, 102));
        Carta8.setForeground(new java.awt.Color(153, 102, 255));
        Carta8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 100, 150));

        Carta9.setBackground(new java.awt.Color(102, 0, 102));
        Carta9.setForeground(new java.awt.Color(153, 102, 255));
        Carta9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 100, 150));

        Carta10.setBackground(new java.awt.Color(102, 0, 102));
        Carta10.setForeground(new java.awt.Color(153, 102, 255));
        Carta10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadly21/Carta.png"))); // NOI18N
        fondoColor.add(Carta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 100, 150));
        fondoColor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 190, 120));
        fondoColor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 190, 120));
        fondoColor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondoColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carta1;
    private javax.swing.JLabel Carta10;
    private javax.swing.JLabel Carta2;
    private javax.swing.JLabel Carta3;
    private javax.swing.JLabel Carta4;
    private javax.swing.JLabel Carta5;
    private javax.swing.JLabel Carta6;
    private javax.swing.JLabel Carta7;
    private javax.swing.JLabel Carta8;
    private javax.swing.JLabel Carta9;
    private javax.swing.JPanel fondoColor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
