/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deadly21;

import static deadly21.InterfazPartidaDeadly21.lista;
import static deadly21.InterfazPartidaDeadly21.listaFinal;
import static deadly21.InterfazPartidaDeadly21.listaInicial;
import static deadly21.InterfazPartidaDeadly21.listaSemis;
import static deadly21.InterfazPartidaDeadly21.ganador;
import static deadly21.InterfazMenuDeadly21.interfazPartida;
import java.awt.Color;

/**
 *
 * @author Agustín
 */
public class InterfazDuelos extends javax.swing.JFrame {
    public void comienzo(){
        jLabel1.setText(listaInicial.obtenerNombreParticipante(0));
        jLabel13.setText(listaInicial.obtenerNombreParticipante(1));
        jLabel14.setText(listaInicial.obtenerNombreParticipante(2));
        jLabel15.setText(listaInicial.obtenerNombreParticipante(3));
        jLabel7.setText(listaInicial.obtenerNombreParticipante(4));
        jLabel8.setText(listaInicial.obtenerNombreParticipante(5));
        jLabel9.setText(listaInicial.obtenerNombreParticipante(6));
        jLabel10.setText(listaInicial.obtenerNombreParticipante(7));
     }
     
    public void semis(){
         comienzo();
        jLabel2.setText(listaSemis.obtenerNombreParticipante(0));
        jLabel16.setText(listaSemis.obtenerNombreParticipante(1));
        jLabel5.setText(listaSemis.obtenerNombreParticipante(2));
        jLabel6.setText(listaSemis.obtenerNombreParticipante(3));
     }
     
     public void finals(){
         semis();
        jLabel12.setText(listaFinal.obtenerNombreParticipante(0));
        jLabel4.setText(listaFinal.obtenerNombreParticipante(1));
         
     }
     
     public void ganador(){
         finals();
         jLabel3.setText(ganador.obtenerNombre());
     }
    /**
     * Creates new form interfazDuelos
     */
    public InterfazDuelos() {
        initComponents();
        setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        setLocationRelativeTo(null);
        if(lista.largo == 8){
            comienzo();
        }
        else if(lista.largo == 4){
            semis();
        }
         else if(lista.largo == 2){
            finals();
        }
         else if(lista.largo == 1){
             ganador();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        flechaCont = new javax.swing.JButton();
        papelDuelos = new javax.swing.JLabel();
        cartelDuelos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 60, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 424, 60, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 60, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 427, 60, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 60, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 60, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 60, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 60, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 60, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 470, 60, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 60, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 80, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 60, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 60, -1));

        flechaCont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Flecha.png"))); // NOI18N
        flechaCont.setBorder(null);
        flechaCont.setBorderPainted(false);
        flechaCont.setContentAreaFilled(false);
        flechaCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                flechaContMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                flechaContMouseExited(evt);
            }
        });
        flechaCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flechaContActionPerformed(evt);
            }
        });
        getContentPane().add(flechaCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 320, 90));

        papelDuelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Duelos.png"))); // NOI18N
        getContentPane().add(papelDuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        cartelDuelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/CartelG.png"))); // NOI18N
        getContentPane().add(cartelDuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flechaContMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaContMouseEntered
        // TODO add your handling code here:

            flechaCont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Flecha2.png")));
        
    }//GEN-LAST:event_flechaContMouseEntered

    private void flechaContMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaContMouseExited
        // TODO add your handling code here:
   
            flechaCont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Flecha.png")));
        
    }//GEN-LAST:event_flechaContMouseExited

    private void flechaContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flechaContActionPerformed
        // TODO add your handling code here:
       setVisible(false);
       interfazPartida.setVisible(true);
       interfazPartida.setEnabled(true);
       
    }//GEN-LAST:event_flechaContActionPerformed

    /**
     * @param args the command line arguments
     */

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartelDuelos;
    private javax.swing.JButton flechaCont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel papelDuelos;
    // End of variables declaration//GEN-END:variables
}
